spring:
  application:
    name: manage_money
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:managemoney_dev}
    username: ${DB_USERNAME:money_manager}
    password: ${DB_PASSWORD:p0F2iwNraBb0V1}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: ${SHOW_SQL:true}
    hibernate:
      ddl-auto: ${HIBERNATE_DDL:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        schema: managemoney
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    org.springframework.web: ${LOG_LEVEL:INFO}
    org.hibernate: ${LOG_LEVEL:INFO}
    com.app.manage_money: ${LOG_LEVEL:DEBUG}